I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 56, in script call
    call scene_9
  File "game/scenes/scene_9.rpy", line 8, in script
    v "Не хочу, мне и здесь нравится."
Exception: Sayer 'v' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 56, in script call
    call scene_9
  File "game/scenes/scene_9.rpy", line 8, in script
    v "Не хочу, мне и здесь нравится."
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'v' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.9.2142
VikaDR 1.0
Sun Oct 17 20:54:36 2021
