I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 110, in script call
    call scene_9 from _call_scene_9
  File "game/scenes/scene_9.rpy", line 18, in script
    dp "Давайте поможем Максиму соблазнить Вику! Для этого выберите те фразы, которые, как вы думаете, соблазнили бы Вику."
Exception: Sayer 'dp' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 110, in script call
    call scene_9 from _call_scene_9
  File "game/scenes/scene_9.rpy", line 18, in script
    dp "Давайте поможем Максиму соблазнить Вику! Для этого выберите те фразы, которые, как вы думаете, соблазнили бы Вику."
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'dp' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.9.2142
VikaDR 1.0
Sun Oct 24 01:58:18 2021
